from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

jrwatch = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'nPM1300-QEAA', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'nPM1300-QEAA'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DFN_QFN:VQFN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm_ThermalVias', 'keywords':None, 'description':'PMIC: LiPo charger + 2x buck + 2x LDO/loadswitch + fuel gauge + ship mode', 'datasheet':None, 'pins':[
            Pin(num='1',name='VOUT1',func=pin_types.PWROUT),
            Pin(num='2',name='PVSS1',func=pin_types.PWRIN),
            Pin(num='3',name='SW1',func=pin_types.OUTPUT),
            Pin(num='4',name='PVDD',func=pin_types.PWRIN),
            Pin(num='5',name='SW2',func=pin_types.OUTPUT),
            Pin(num='6',name='PVSS2',func=pin_types.PWRIN),
            Pin(num='7',name='GPIO0',func=pin_types.BIDIR),
            Pin(num='8',name='GPIO1',func=pin_types.BIDIR),
            Pin(num='9',name='GPIO2',func=pin_types.BIDIR),
            Pin(num='10',name='GPIO3',func=pin_types.BIDIR),
            Pin(num='11',name='GPIO4',func=pin_types.BIDIR),
            Pin(num='12',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='13',name='SDA',func=pin_types.BIDIR),
            Pin(num='14',name='SCL',func=pin_types.INPUT),
            Pin(num='15',name='SHPHLD',func=pin_types.INPUT),
            Pin(num='16',name='VSET2',func=pin_types.INPUT),
            Pin(num='17',name='VSET1',func=pin_types.INPUT),
            Pin(num='18',name='NTC',func=pin_types.INPUT),
            Pin(num='19',name='VBAT',func=pin_types.PWRIN),
            Pin(num='20',name='VSYS',func=pin_types.PWROUT),
            Pin(num='21',name='VBUS',func=pin_types.PWRIN),
            Pin(num='22',name='VBUSOUT',func=pin_types.PWROUT),
            Pin(num='23',name='CC1',func=pin_types.BIDIR),
            Pin(num='24',name='CC2',func=pin_types.BIDIR),
            Pin(num='25',name='LED0',func=pin_types.OPENCOLL),
            Pin(num='26',name='LED1',func=pin_types.OPENCOLL),
            Pin(num='27',name='LED2',func=pin_types.OPENCOLL),
            Pin(num='28',name='LSIN1',func=pin_types.PWRIN),
            Pin(num='29',name='LSOUT1',func=pin_types.PWROUT),
            Pin(num='30',name='LSIN2',func=pin_types.PWRIN),
            Pin(num='31',name='LSOUT2',func=pin_types.PWROUT),
            Pin(num='32',name='VOUT2',func=pin_types.PWROUT),
            Pin(num='33',name='EP_AVSS',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'C_0603', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_0603'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'C_0603', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'C_0402', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_0402'}), 'ref_prefix':'C', 'fplist':None, 'footprint':'Capacitor_SMD:C_0402_1005Metric', 'keywords':None, 'description':'C_0402', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'DFE201612E-2R2M', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DFE201612E-2R2M'}), 'ref_prefix':'L', 'fplist':None, 'footprint':'JRWatch:L_Murata_DFE201612E_2016', 'keywords':None, 'description':'2.2 uH power inductor, 116 mOhm, Isat 2.4 A (nPM1300 buck)', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'R_0402', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R_0402'}), 'ref_prefix':'R', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'R_0402', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'NCP15XH103F03RC', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'NCP15XH103F03RC'}), 'ref_prefix':'RT', 'fplist':None, 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':None, 'description':'NTC 10k 1% B=3380 (battery temperature, nPM1300 NTC)', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SM02B-SRSS-TB', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SM02B-SRSS-TB'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_JST:JST_SH_SM02B-SRSS-TB_1x02-1MP_P1.00mm_Horizontal', 'keywords':None, 'description':'Battery connector, JST-SH 2P right angle. PIN 1 = BAT+ (verify pigtail!)', 'datasheet':None, 'pins':[
            Pin(num='1',name='BAT+',func=pin_types.PASSIVE),
            Pin(num='2',name='BAT-',func=pin_types.PASSIVE),
            Pin(num='MP',name='MP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'MDBT50Q-1MV2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MDBT50Q-1MV2'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'RF_Module:Raytac_MDBT50Q', 'keywords':None, 'description':'BLE module, nRF52840, chip antenna, BT5.x certified', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='P1.10',func=pin_types.BIDIR),
            Pin(num='4',name='P1.11',func=pin_types.BIDIR),
            Pin(num='5',name='P1.12',func=pin_types.BIDIR),
            Pin(num='6',name='P1.13',func=pin_types.BIDIR),
            Pin(num='7',name='P1.14',func=pin_types.BIDIR),
            Pin(num='8',name='P1.15',func=pin_types.BIDIR),
            Pin(num='9',name='P0.03/AIN1',func=pin_types.BIDIR),
            Pin(num='10',name='P0.29/AIN5',func=pin_types.BIDIR),
            Pin(num='11',name='P0.02/AIN0',func=pin_types.BIDIR),
            Pin(num='12',name='P0.31/AIN7',func=pin_types.BIDIR),
            Pin(num='13',name='P0.28/AIN4',func=pin_types.BIDIR),
            Pin(num='14',name='P0.30/AIN6',func=pin_types.BIDIR),
            Pin(num='15',name='GND',func=pin_types.PWRIN),
            Pin(num='16',name='P0.27',func=pin_types.BIDIR),
            Pin(num='17',name='P0.00/XL1',func=pin_types.BIDIR),
            Pin(num='18',name='P0.01/XL2',func=pin_types.BIDIR),
            Pin(num='19',name='P0.26',func=pin_types.BIDIR),
            Pin(num='20',name='P0.04/AIN2',func=pin_types.BIDIR),
            Pin(num='21',name='P0.05/AIN3',func=pin_types.BIDIR),
            Pin(num='22',name='P0.06',func=pin_types.BIDIR),
            Pin(num='23',name='P0.07',func=pin_types.BIDIR),
            Pin(num='24',name='P0.08',func=pin_types.BIDIR),
            Pin(num='25',name='P1.08',func=pin_types.BIDIR),
            Pin(num='26',name='P1.09',func=pin_types.BIDIR),
            Pin(num='27',name='P0.11',func=pin_types.BIDIR),
            Pin(num='28',name='VDD',func=pin_types.PWRIN),
            Pin(num='29',name='P0.12',func=pin_types.BIDIR),
            Pin(num='30',name='VDDH',func=pin_types.PWRIN),
            Pin(num='31',name='DCCH',func=pin_types.NOCONNECT),
            Pin(num='32',name='VBUS',func=pin_types.PWRIN),
            Pin(num='33',name='GND',func=pin_types.PWRIN),
            Pin(num='34',name='D-',func=pin_types.BIDIR),
            Pin(num='35',name='D+',func=pin_types.BIDIR),
            Pin(num='36',name='P0.14',func=pin_types.BIDIR),
            Pin(num='37',name='P0.13',func=pin_types.BIDIR),
            Pin(num='38',name='P0.16',func=pin_types.BIDIR),
            Pin(num='39',name='P0.15',func=pin_types.BIDIR),
            Pin(num='40',name='P0.18/nRESET',func=pin_types.BIDIR),
            Pin(num='41',name='P0.17',func=pin_types.BIDIR),
            Pin(num='42',name='P0.19',func=pin_types.BIDIR),
            Pin(num='43',name='P0.21',func=pin_types.BIDIR),
            Pin(num='44',name='P0.20',func=pin_types.BIDIR),
            Pin(num='45',name='P0.23',func=pin_types.BIDIR),
            Pin(num='46',name='P0.22',func=pin_types.BIDIR),
            Pin(num='47',name='P1.00/SWO',func=pin_types.BIDIR),
            Pin(num='48',name='P0.24',func=pin_types.BIDIR),
            Pin(num='49',name='P0.25',func=pin_types.BIDIR),
            Pin(num='50',name='P1.02',func=pin_types.BIDIR),
            Pin(num='51',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='52',name='P0.09/NFC1',func=pin_types.BIDIR),
            Pin(num='53',name='SWDCLK',func=pin_types.INPUT),
            Pin(num='54',name='P0.10/NFC2',func=pin_types.BIDIR),
            Pin(num='55',name='GND',func=pin_types.PWRIN),
            Pin(num='56',name='P1.04',func=pin_types.BIDIR),
            Pin(num='57',name='P1.06',func=pin_types.BIDIR),
            Pin(num='58',name='P1.07',func=pin_types.BIDIR),
            Pin(num='59',name='P1.05',func=pin_types.BIDIR),
            Pin(num='60',name='P1.03',func=pin_types.BIDIR),
            Pin(num='61',name='P1.01',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'Q13FC13500004', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Q13FC13500004'}), 'ref_prefix':'Y', 'fplist':None, 'footprint':'Crystal:Crystal_SMD_3215-2Pin_3.2x1.5mm', 'keywords':None, 'description':'32.768 kHz crystal, CL=12.5 pF, +/-20 ppm (FC-135R family)', 'datasheet':None, 'pins':[
            Pin(num='1',name='X1',func=pin_types.PASSIVE),
            Pin(num='2',name='X2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'TC2030-IDC-NL', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TC2030-IDC-NL'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector:Tag-Connect_TC2030-IDC-NL_2x03_P1.27mm_Vertical', 'keywords':None, 'description':'SWD pads (Tag-Connect, no part fitted)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VTREF',func=pin_types.PWRIN),
            Pin(num='2',name='SWDIO',func=pin_types.BIDIR),
            Pin(num='3',name='nRESET',func=pin_types.BIDIR),
            Pin(num='4',name='SWDCLK',func=pin_types.BIDIR),
            Pin(num='5',name='GND',func=pin_types.PWRIN),
            Pin(num='6',name='SWO',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'TYPE-C-31-M-12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TYPE-C-31-M-12'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_USB:USB_C_Receptacle_HRO_TYPE-C-31-M-12', 'keywords':None, 'description':'USB-C receptacle 16P (charge + FS data)', 'datasheet':None, 'pins':[
            Pin(num='A1',name='GND',func=pin_types.PWRIN),
            Pin(num='A12',name='GND',func=pin_types.PWRIN),
            Pin(num='B1',name='GND',func=pin_types.PWRIN),
            Pin(num='B12',name='GND',func=pin_types.PWRIN),
            Pin(num='A4',name='VBUS',func=pin_types.PWRIN),
            Pin(num='A9',name='VBUS',func=pin_types.PWRIN),
            Pin(num='B4',name='VBUS',func=pin_types.PWRIN),
            Pin(num='B9',name='VBUS',func=pin_types.PWRIN),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR),
            Pin(num='A6',name='DP1',func=pin_types.BIDIR),
            Pin(num='B6',name='DP2',func=pin_types.BIDIR),
            Pin(num='A7',name='DM1',func=pin_types.BIDIR),
            Pin(num='B7',name='DM2',func=pin_types.BIDIR),
            Pin(num='A8',name='SBU1',func=pin_types.NOCONNECT),
            Pin(num='B8',name='SBU2',func=pin_types.NOCONNECT),
            Pin(num='SH',name='SHIELD',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':None, 'description':'USB ESD protection array (flow-through)', 'datasheet':None, 'pins':[
            Pin(num='1',name='IO1',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='IO2',func=pin_types.PASSIVE),
            Pin(num='4',name='IO2B',func=pin_types.PASSIVE),
            Pin(num='5',name='VBUS',func=pin_types.PWRIN),
            Pin(num='6',name='IO1B',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'BMI270', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BMI270'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_LGA:Bosch_LGA-14_3x2.5mm_P0.5mm', 'keywords':None, 'description':'6-axis IMU, low-power any-motion wake + step counter, SPI 4-wire', 'datasheet':None, 'pins':[
            Pin(num='1',name='SDO',func=pin_types.TRISTATE),
            Pin(num='2',name='ASDX',func=pin_types.INPUT),
            Pin(num='3',name='ASCX',func=pin_types.INPUT),
            Pin(num='4',name='INT1',func=pin_types.OUTPUT),
            Pin(num='5',name='VDDIO',func=pin_types.PWRIN),
            Pin(num='6',name='GNDIO',func=pin_types.PWRIN),
            Pin(num='7',name='GND',func=pin_types.PWRIN),
            Pin(num='8',name='VDD',func=pin_types.PWRIN),
            Pin(num='9',name='INT2',func=pin_types.NOCONNECT),
            Pin(num='10',name='OCSB',func=pin_types.NOCONNECT),
            Pin(num='11',name='OSDO',func=pin_types.NOCONNECT),
            Pin(num='12',name='CSB',func=pin_types.INPUT),
            Pin(num='13',name='SCX',func=pin_types.INPUT),
            Pin(num='14',name='SDX',func=pin_types.INPUT)] }),
        Part(**{ 'name':'FH12A-10S-0.5SH', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'FH12A-10S-0.5SH'}), 'ref_prefix':'J', 'fplist':None, 'footprint':'Connector_FFC-FPC:Hirose_FH12-10S-0.5SH_1x10-1MP_P0.50mm_Horizontal', 'keywords':None, 'description':'Display FPC connector — mates LS013B7DH03 tail terminal (11-k) on pad k: the 180-degree fold under the panel flips the contact face, so the top-contact FH12A sees the terminal order reversed (Sharp fig 8-1)', 'datasheet':None, 'pins':[
            Pin(num='1',name='VSSA',func=pin_types.PWRIN),
            Pin(num='2',name='VSS',func=pin_types.PWRIN),
            Pin(num='3',name='EXTMODE',func=pin_types.INPUT),
            Pin(num='4',name='VDD',func=pin_types.PWRIN),
            Pin(num='5',name='VDDA',func=pin_types.PWRIN),
            Pin(num='6',name='DISP',func=pin_types.INPUT),
            Pin(num='7',name='EXTCOMIN',func=pin_types.INPUT),
            Pin(num='8',name='SCS',func=pin_types.INPUT),
            Pin(num='9',name='SI',func=pin_types.INPUT),
            Pin(num='10',name='SCLK',func=pin_types.INPUT),
            Pin(num='MP',name='MP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'SKRTLAE010', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SKRTLAE010'}), 'ref_prefix':'SW', 'fplist':None, 'footprint':'Button_Switch_SMD:SW_Push_1P1T-MP_NO_Horizontal_Alps_SKRTLAE010', 'keywords':None, 'description':'Side-actuated tact switch 4.5x3.4 mm', 'datasheet':None, 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='MP',name='MP',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'ESD9B5.0ST5G', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESD9B5.0ST5G'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-923', 'keywords':None, 'description':'Bidirectional ESD TVS, 5.0 V working (SHPHLD swings to VBAT)', 'datasheet':None, 'pins':[
            Pin(num='1',name='A1',func=pin_types.PASSIVE),
            Pin(num='2',name='A2',func=pin_types.PASSIVE)] }),
        Part(**{ 'name':'ESD9B3.3ST5G', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESD9B3.3ST5G'}), 'ref_prefix':'D', 'fplist':None, 'footprint':'Diode_SMD:D_SOD-923', 'keywords':None, 'description':'Bidirectional ESD TVS, 3.3 V working (logic-level button line)', 'datasheet':None, 'pins':[
            Pin(num='1',name='A1',func=pin_types.PASSIVE),
            Pin(num='2',name='A2',func=pin_types.PASSIVE)] })])