manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.1.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - segger
          - mbedtls
          - tinycrypt
          - picolibc

  self:
    path: jrwatch/firmware
